sonar.projectKey=frontend-project-46
sonar.organization=tryggvid
sonar.host.url=https://sonarcloud.io

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.test.js,**/__tests__/**,**/__fixtures__/**,**/bin/**,**/node_modules/**,**/coverage/**
sonar.exclusions=node_modules/**,coverage/**,__fixtures__/**,**/*.test.js,**/bin/**,**/actual.txt

# Игнорируем дублирование для тестов
sonar.cpd.exclusions=**/__tests__/**,**/__fixtures__/**,**/node_modules/**

# Настройки безопасности
sonar.javascript.ignore.header.comments=true

sonar.sourceEncoding=UTF-8
