sonar.projectKey=frontend-project-46
sonar.organization=tryggvid
sonar.host.url=https://sonarcloud.io

# Путь к файлу покрытия
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Исключаем тесты и фикстуры из покрытия
sonar.coverage.exclusions=**/*.test.js,**/__tests__/**,**/__fixtures__/**,**/bin/**,**/node_modules/**,**/coverage/**

# Исключаем из анализа
sonar.exclusions=node_modules/**,coverage/**,__fixtures__/**,**/*.test.js,**/bin/**,**/actual.txt,**/actual_output.txt

sonar.sourceEncoding=UTF-8
